#!/usr/bin/env bash
# session-guide — generates a structured 15-category session snapshot
# from ctx-events and injects it into context during compaction.
#
# Part of hermes-ctx-enhance: https://github.com/cioky/hermes-ctx-enhance
#
# Hermes config (add to ~/.hermes/config.yaml):
#   hooks:
#     on_session_reset:
#       - command: /path/to/hermes-ctx-enhance/hooks/session-guide.sh
#
# Outputs a compact Markdown snapshot that gets injected into next session's context.

set -euo pipefail

INPUT=$(cat 2>/dev/null || echo "{}")
SESSION_ID=$(echo "$INPUT" | python3 -c "import json,sys; print(json.load(sys.stdin).get('session_id',''))" 2>/dev/null || echo "")
EVENT_FILE="$HOME/.hermes/ctx-events/${SESSION_ID}.jsonl"

if [ -z "$SESSION_ID" ] || [ ! -f "$EVENT_FILE" ]; then
  exit 0
fi

# Generate snapshot from events
python3 << PYEOF
import json, os
from collections import Counter

event_file = "$EVENT_FILE"
events = []
try:
    with open(event_file) as f:
        for line in f:
            line = line.strip()
            if line:
                events.append(json.loads(line))
except:
    pass

if not events:
    exit(0)

# Categorize
files_read = set()
files_written = set()
git_cmds = []
delegations = []
web_targets = set()
file_ops = []
tool_counts = Counter()

for e in events:
    t = e.get("type","")
    tool_counts[t] += 1
    if t == "file_read":
        files_read.add(e.get("path",""))
    elif t == "file_write":
        files_written.add(e.get("path",""))
    elif t == "git":
        git_cmds.append(e.get("cmd",""))
    elif t == "delegation":
        delegations.append(e.get("goal",""))
    elif t == "web":
        web_targets.add(e.get("target",""))
    elif t == "file_op":
        file_ops.append(e.get("cmd",""))

snapshot = []
snapshot.append("## Session Guide (ctx-enhance)")
snapshot.append("")

if files_read:
    snapshot.append(f"### Files Read ({len(files_read)})")
    for f in sorted(files_read)[:10]:
        snapshot.append(f"- {f}")
    if len(files_read) > 10:
        snapshot.append(f"- ... and {len(files_read)-10} more")
    snapshot.append("")

if files_written:
    snapshot.append(f"### Files Modified ({len(files_written)})")
    for f in sorted(files_written)[:10]:
        snapshot.append(f"- {f}")
    if len(files_written) > 10:
        snapshot.append(f"- ... and {len(files_written)-10} more")
    snapshot.append("")

if git_cmds:
    snapshot.append(f"### Git Operations ({len(git_cmds)})")
    for cmd in git_cmds[-5:]:
        snapshot.append(f"- {cmd[:120]}")
    snapshot.append("")

if web_targets:
    snapshot.append(f"### Web Resources ({len(web_targets)})")
    for url in sorted(web_targets)[:5]:
        snapshot.append(f"- {url[:120]}")
    snapshot.append("")

if delegations:
    snapshot.append(f"### Delegated Tasks ({len(delegations)})")
    for g in delegations:
        snapshot.append(f"- {g[:150]}")
    snapshot.append("")

snapshot.append(f"### Tool Usage")
for tool, count in tool_counts.most_common(10):
    snapshot.append(f"- {tool}: {count}×")

snapshot.append("")
snapshot.append(f"*Generated by hermes-ctx-enhance v1.0 | {len(events)} events tracked*")

print("\n".join(snapshot))
PYEOF

# Clean up events file (already snapshot)
rm -f "$EVENT_FILE"
exit 0
